### ISSUE TITLE
Doesn't work in Safari 9.1.2 on mac

### ISSUE THREAD

**Issue by BookOwl** [PullJosh/game-of-life-machine#2]
There are no errors in the console, but it doesn't do anything.

**Comment by PullJosh** [comment]
[Safari must be broken.](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/)

**Comment by PullJosh** [comment]
[Safari must be broken.](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/)

**Comment by BookOwl** [comment]
Doesn't work on iOS either.

**Comment by PullJosh** [comment]
Apple is the worst... :frowning:

**Comment by BookOwl** [comment]
I just tried this again in Safari 10.0.3, and it works!

**Comment by PullJosh** [comment]
Awesome! :)
